from os import listdir
from os.path import isfile, join
from random import randrange


source_dir = './files/to_install_on_mt4'
destination_dir = '/home/kevin.bruton/.wine/drive_c/MT4/MQL4/Files/EaTemplates/'

template = '<chart>\n'
template2 = """scale=8
graph=1
fore=0
grid=0
volume=0
scroll=1
shift=0
ohlc=1
one_click=0
one_click_btn=1
askline=0
days=0
descriptions=0
shift_size=20
fixed_pos=0
window_left=88
window_top=88
window_right=1531
window_bottom=661
window_type=3
background_color=16777215
foreground_color=0
barup_color=32768
bardown_color=255
bullcandle_color=32768
bearcandle_color=255
chartline_color=0
volumes_color=32768
grid_color=12632256
askline_color=17919
stops_color=17919

<window>
height=100
fixed_height=0
<indicator>
name=main
<object>
type=23
object_name=line1
period_flags=0
create_time=1685900189
description=EURUSD_H1_221101001
color=16777215
font=Tahoma
fontsize=9
angle=0
anchor_pos=6
background=0
filling=0
selectable=1
hidden=0
zorder=0
corner=1
x_distance=5
y_distance=20
</object>
<object>
type=23
object_name=linec
period_flags=0
create_time=1685900189
description=Generated by StrategyQuant EA Wizard
color=16777215
font=Tahoma
fontsize=8
angle=0
anchor_pos=6
background=0
filling=0
selectable=1
hidden=0
zorder=0
corner=1
x_distance=5
y_distance=36
</object>
<object>
type=23
object_name=line2
period_flags=0
create_time=1685900189
description=------------------------------------------
color=16777215
font=Tahoma
fontsize=8
angle=0
anchor_pos=6
background=0
filling=0
selectable=1
hidden=0
zorder=0
corner=1
x_distance=5
y_distance=48
</object>
<object>
type=23
object_name=lines
period_flags=0
create_time=1685900189
description=Last Signal:  -
color=16777215
font=Tahoma
fontsize=9
angle=0
anchor_pos=6
background=0
filling=0
selectable=1
hidden=0
zorder=0
corner=1
x_distance=5
y_distance=64
</object>
<object>
type=23
object_name=lineopl
period_flags=0
create_time=1685900189
description=Open P/L: -
color=16777215
font=Tahoma
fontsize=8
angle=0
anchor_pos=6
background=0
filling=0
selectable=1
hidden=0
zorder=0
corner=1
x_distance=5
y_distance=80
</object>
<object>
type=23
object_name=linea
period_flags=0
create_time=1685900189
description=Account Balance: -
color=16777215
font=Tahoma
fontsize=8
angle=0
anchor_pos=6
background=0
filling=0
selectable=1
hidden=0
zorder=0
corner=1
x_distance=5
y_distance=96
</object>
<object>
type=23
object_name=lineto
period_flags=0
create_time=1685900189
description=Total profits/losses so far: -/-
color=16777215
font=Tahoma
fontsize=8
angle=0
anchor_pos=6
background=0
filling=0
selectable=1
hidden=0
zorder=0
corner=1
x_distance=5
y_distance=112
</object>
<object>
type=23
object_name=linetp
period_flags=0
create_time=1685900189
description=Total P/L so far: -
color=16777215
font=Tahoma
fontsize=8
angle=0
anchor_pos=6
background=0
filling=0
selectable=1
hidden=0
zorder=0
corner=1
x_distance=5
y_distance=128
</object>
</indicator>
</window>

<expert>
"""

onlyfiles = [f for f in listdir(source_dir) if isfile(join(source_dir, f))]
onlyMt4Files = [f[:-4] for f in onlyfiles if f[-3:] == 'mq4']

for filename in onlyMt4Files:
    print(f'Processing {filename}...')
    filename_parts = filename.split('_')
    symbol = filename_parts[0]
    period = filename_parts[1]
    magic = filename_parts[2].split('.')[0]

    # Generate chart ID
    chart_id = ''
    for i in range(18):
        chart_id += str(randrange(10))
    
    template = '<chart>\n'
    template += f'id={chart_id}\n'
    template += f'symbol={symbol}\n'

    # Get period in minutes
    mins = 60
    if period == 'H1': mins = 60
    if period == 'H4': mins = 240
    if period == 'M30': mins = 30

    template += f'period={mins}\n'

    # Get decimals
    decimals = 5
    if symbol == 'EURUSD':  decimals = 5
    if symbol == 'XAUUSD':  decimals = 2
    if symbol == 'WS30':    decimals = 0
    if symbol == 'NDX':     decimals = 1
    if symbol == 'AUDUSD':  decimals = 5

    template += 'leftpos=1296\n'
    template += f'digits={decimals}\n'

    template += template2

    # Get name
    name = f'{symbol}_{period}_{magic}'
    template += f'name={name}\n'

    template += 'flags=279\n'
    template += 'window_num=0\n'
    template += '<inputs>\n'

    # Get inputs
    file1 = open(source_dir + '/' + filename + '.mq4', 'r')
    lines = file1.readlines()
    file1.close()
    for line in lines:
        line_parts = line.split(' ')
        if len(line_parts) and line_parts[0] == 'extern':
            input_name = line_parts[2]
            if line_parts[4][0] == '"':
                input_value = line_parts[4].split('"')[1]
            else:
                input_value = line_parts[4].split(';')[0]
            template += f'{input_name}={input_value}\n'
    
    template += '</inputs>\n'
    template += '</expert>\n'
    template += '</chart>\n'

    template_file = open(destination_dir + f'{symbol}_{period}_{magic}.tpl', 'w')
    template_file.write(template)
    template_file.close()