[project]
name = "autoinvesting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "pywinauto>=0.6.9",
    "quantstats>=0.0.64",
]
