import './auto-investing.js'
import './pages/login.js'
import './pages/home.js'
import './pages/add-strategy.js'
import './components/chart.js'

import '@kor-ui/kor/components/page/index.js'
import '@kor-ui/kor/components/app-bar'
import '@kor-ui/kor/components/card'
import '@kor-ui/kor/components/input'
import '@kor-ui/kor/components/button'
import '@kor-ui/kor/components/text'
import '@kor-ui/kor/components/textarea'
import '@kor-ui/kor/components/badge'
import '@kor-ui/kor/components/menu-item'
import '@kor-ui/kor/components/table'
