CREATE TABLE Trades (
  orderId VARCHAR(55) NOT NULL,
  runId VARCHAR(55) NOT NULL,
  symbol VARCHAR(55),
  orderType VARCHAR(55),
  openTime DATETIME,
  closeTime DATETIME,
  openPrice FLOAT,
  closePrice FLOAT,
  size DECIMAL(4,2),
  profit DECIMAL(10,2),
  closeType VARCHAR(55),
  comment VARCHAR(255),
  sl FLOAT,
  tp FLOAT,
  swap DECIMAL(10,2),
  commission DECIMAL(10,2),
  PRIMARY KEY (orderId),
  FOREIGN KEY (runId) REFERENCES StrategyRuns(runId)
);
